---
  name: Create class diagram

  on:
    pull_request:
      types: [review_requested]
    
    pull_request_review:
      types: [submitted]

  jobs:
    create-class-diagram:
      name: Create class diagram
      runs-on: ubuntu-latest
      
      steps:
        - name: Check out repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
          with:
            ref: ${{ github.event.pull_request.head.ref }}

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.5.28"  # install a specific version of uv
            enable-cache: true

        - name: Install the project
          run: uv sync

        - name: Install graphviz
          run: sudo apt-get install -y graphviz graphviz-dev

        - name: Install erdantic
          run: uv add "erdantic>=1.0.5"
        
        - name: Register custom erdantic plugin for pydantic and generate schema diagram files
          run: uv run python ./.github/workflows/erdantic-pydantic-plugin.py

        - name: Stage schema diagram files
          run: git add ./docs

        - name: Commit and push changes
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "build(docs): update schema diagram files" || echo "No changes to commit"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
