name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [checks]
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Set up rye
        uses: eifinger/setup-rye@v4.2.1
        id: setup-rye
        with:
          enable-cache: true
          cache-prefix: ${{ matrix.python-version }}

      - name: Pin python-version @ ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: |
          rye sync --no-lock

      - name: Unit test using pytest
        run: rye test