name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [checks]
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up PDM @ ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          architecture: x64

      - name: Install dependencies
        run: pdm install

      - name: Unit test using pytest
        run: pdm run pytest