name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [checks]
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up PDM @ ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          architecture: x64
          enable-pep582: true
        env:
          PDM_DEPS: "urllib3<2"

      - name: Install dependencies
        run: pdm install

      - name: Unit test using pytest
        run: pdm run pytest

      - name: Install graphviz
        run: sudo apt-get install -y graphviz graphviz-dev

      - name: Install erdantic
        run: pdm add erdantic

      - name: Generate schema diagram files
        run: pdm run python -c '$COMMAND'
        env:
          COMMAND: |
            import erdantic as erd
            from psdm.steadystate_case.case import Case as SteadystateCase
            from psdm.topology.topology import Topology
            from psdm.topology_case.case import Case as TopologyCase
            from pathlib import Path
            f_top = Path(f"./schema/1/topology.png")
            f_top.parent.mkdir(exist_ok=True, parents=True)
            erd.create(Topology).draw(f_top)
            f_topc = Path(f"./schema/1/topology_case.png")
            f_topc.parent.mkdir(exist_ok=True, parents=True)
            erd.create(TopologyCase).draw(f_topc)
            f_ssc = Path(f"./schema/1/steady_state_case.png")
            f_ssc.parent.mkdir(exist_ok=True, parents=True)
            erd.create(SteadystateCase).draw(f_ssc)

      - name: Copy diagrams to docs
        run: cp -rf./schema/1/*.png ./docs/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path:  ./docs
